spring:
  profiles:
    active:
      - security
      - db
  application:
    name: member-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${MEMBER_DB_SCHEMA}