spring:
  profiles:
    include:
      - security
      - db
  application:
    name: member-service

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

springdoc:
  api-docs:
    path: /api/member/oas.json
  writer-with-default-pretty-printer: true

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${MEMBER_DB_SCHEMA}
