spring:
  profiles:
    active:
      -  security
      - db
  application:
    name: member-service

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api/member/oas.json
  writer-with-default-pretty-printer: true