spring:
  application:
    name: product-service
  profiles:
    include:
      - db
      - security

server:
  port: 8083
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /api/product/oas.json
  writer-with-default-pretty-printer: true

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${PRODUCT_DB_SCHEMA}
  service-key: ${SERVICE_KEY}
