spring:
  application:
    name: product-service
  profiles:
    active:
      - db
      - security

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${PRODUCT_DB_SCHEMA}