spring:
  application:
    name: product-service
  profiles:
    active:
      - db
      - security

server:
  port: 8083
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api/product/oas.json
    writer-with-default-pretty-printer: true
    defaultZone: ${EUREKA_URL}

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${PRODUCT_DB_SCHEMA}
