spring:
  application:
    name: crawler-service
  kafka:
    bootstrap-servers: localhost:9092
  profiles:
    include:
      - db
      - security

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /api/crawler/oas.json
  writer-with-default-pretty-printer: true

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${CRAWLER_DB_SCHEMA}
  service-key: ${SERVICE_KEY}