spring:
  application:
    name: crawler-service
  kafka:
    bootstrap-servers: localhost:9092
  profiles:
    active:
      - db
      - security

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

service:
  gateway-host: ${GATEWAY_HOST}
  db_schema: ${CRAWLER_DB_SCHEMA}